import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import styles from 'common/styles/Home.module.css'
import FormTest from 'common/widget/FormTest'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<h1>test</h1>
				<FormTest />
			</main>
		</>
	)
}
